[2023-02-15T01:13:09.062+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [queued]>
[2023-02-15T01:13:09.075+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [queued]>
[2023-02-15T01:13:09.075+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:13:09.075+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-15T01:13:09.076+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:13:09.100+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_data> on 2023-02-15 01:10:59.172626+00:00
[2023-02-15T01:13:09.109+0000] {standard_task_runner.py:55} INFO - Started process 848 to run task
[2023-02-15T01:13:09.112+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'download_data', 'manual__2023-02-15T01:10:59.172626+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/firts_dag.py', '--cfg-path', '/tmp/tmp0dpw86kc']
[2023-02-15T01:13:09.113+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask download_data
[2023-02-15T01:13:09.199+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [running]> on host ca65f84028ad
[2023-02-15T01:13:09.344+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T01:10:59.172626+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T01:10:59.172626+00:00
[2023-02-15T01:13:09.346+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T01:13:09.347+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'scrapy crawl linkedin_jobs -O json.json']
[2023-02-15T01:13:09.366+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T01:13:09.368+0000] {subprocess.py:93} INFO - /bin/bash: line 1: scrapy: command not found
[2023-02-15T01:13:09.369+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-15T01:13:09.387+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-15T01:13:09.393+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_dag, task_id=download_data, execution_date=20230215T011059, start_date=20230215T011309, end_date=20230215T011309
[2023-02-15T01:13:09.421+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task download_data (Bash command failed. The command returned a non-zero exit code 127.; 848)
[2023-02-15T01:13:09.444+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-15T01:13:09.469+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
