[2023-02-15T01:12:04.421+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:12:03.207856+00:00 [queued]>
[2023-02-15T01:12:04.435+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:12:03.207856+00:00 [queued]>
[2023-02-15T01:12:04.436+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:12:04.436+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-15T01:12:04.436+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:12:04.468+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_data> on 2023-02-15 01:12:03.207856+00:00
[2023-02-15T01:12:04.480+0000] {standard_task_runner.py:55} INFO - Started process 772 to run task
[2023-02-15T01:12:04.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'download_data', 'manual__2023-02-15T01:12:03.207856+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/firts_dag.py', '--cfg-path', '/tmp/tmpkfpnefmm']
[2023-02-15T01:12:04.487+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask download_data
[2023-02-15T01:12:04.591+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.download_data manual__2023-02-15T01:12:03.207856+00:00 [running]> on host ca65f84028ad
[2023-02-15T01:12:04.725+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T01:12:03.207856+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T01:12:03.207856+00:00
[2023-02-15T01:12:04.726+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T01:12:04.727+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'scrapy crawl linkedin_jobs -O json.json']
[2023-02-15T01:12:04.746+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T01:12:04.747+0000] {subprocess.py:93} INFO - /bin/bash: line 1: scrapy: command not found
[2023-02-15T01:12:04.748+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-15T01:12:04.763+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-15T01:12:04.768+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_dag, task_id=download_data, execution_date=20230215T011203, start_date=20230215T011204, end_date=20230215T011204
[2023-02-15T01:12:04.789+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task download_data (Bash command failed. The command returned a non-zero exit code 127.; 772)
[2023-02-15T01:12:04.816+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-15T01:12:04.842+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
